#pragma once

#define VIDEO_TYPE_NONE 0
#define VIDEO_TYPE_H264 1
#define VIDEO_TYPE_H265 2
#define VIDEO_TYPE_RTP_H264 3
#define VIDEO_TYPE_RTP_H265 4


// Video link profiles: 5 profiles for video link quality management; 1 profile for PIP; rest: unused

#define MAX_VIDEO_LINK_PROFILES 8

#define VIDEO_PROFILE_HIGH_QUALITY 0
#define VIDEO_PROFILE_HIGH_PERF 1
#define VIDEO_PROFILE_LONG_RANGE 2
#define VIDEO_PROFILE_USER 3
#define VIDEO_PROFILE_NA1 4
#define VIDEO_PROFILE_PIP 5
#define VIDEO_PROFILE_LAST 6

#define VIDEO_PROFILE_FLAGS_MASK_NOISE ((u32)0x03)
#define VIDEO_PROFILE_FLAG_USE_HIGHER_DATARATE ((u32)(((u32)0x01)<<2))
#define VIDEO_PROFILE_FLAGS_HIGHER_DATARATE_MASK ((u32) ((((u32)0x01)<<3) | (((u32)0x01)<<4)) )
#define VIDEO_PROFILE_FLAGS_HIGHER_DATARATE_MASK_SHIFT 3

#define VIDEO_PROFILE_ENCODING_FLAG_ENABLE_RETRANSMISSIONS ((u32)(((u32)0x01)<<3))
#define VIDEO_PROFILE_ENCODING_FLAG_ENABLE_ADAPTIVE_VIDEO_KEYFRAME ((u32)(((u32)0x01)<<4))
#define VIDEO_PROFILE_ENCODING_FLAG_ENABLE_ADAPTIVE_VIDEO_LINK ((u32)(((u32)0x01)<<5))
#define VIDEO_PROFILE_ENCODING_FLAG_ADAPTIVE_VIDEO_LINK_USE_CONTROLLER_INFO_TOO ((u32)(((u32)0x01)<<6))
#define VIDEO_PROFILE_ENCODING_FLAG_ADAPTIVE_VIDEO_LINK_GO_LOWER_ON_LINK_LOST ((u32)(((u32)0x01)<<7))
#define VIDEO_PROFILE_ENCODING_FLAG_MAX_RETRANSMISSION_WINDOW_MASK ((u32)(0x0000FF00))
#define VIDEO_PROFILE_ENCODING_FLAG_MASK_RETRANSMISSIONS_DUPLICATION_PERCENT ((u32)(0xFF<<16))
#define VIDEO_PROFILE_ENCODING_FLAG_RETRANSMISSIONS_DUPLICATION_PERCENT_AUTO ((u32)(0xFF<<16))
#define VIDEO_PROFILE_ENCODING_FLAG_USE_MEDIUM_ADAPTIVE_VIDEO ((u32)(((u32)0x01)<<24))
#define VIDEO_PROFILE_ENCODING_FLAG_ENABLE_VIDEO_ADAPTIVE_H264_QUANTIZATION ((u32)(((u32)0x01)<<25))
#define VIDEO_PROFILE_ENCODING_FLAG_VIDEO_ADAPTIVE_QUANTIZATION_STRENGTH_HIGH ((u32)(((u32)0x01)<<26))
#define VIDEO_PROFILE_ENCODING_FLAG_AUTO_EC_SCHEME ((u32)(((u32)0x01)<<27))
#define VIDEO_PROFILE_ENCODING_FLAG_ONE_WAY_FIXED_VIDEO ((u32)(((u32)0x01)<<28))
#define VIDEO_PROFILE_ENCODING_FLAG_EC_SCHEME_SPREAD_FACTOR_HIGHBIT ((u32)(((u32)0x01)<<29))
#define VIDEO_PROFILE_ENCODING_FLAG_EC_SCHEME_SPREAD_FACTOR_LOWBIT ((u32)(((u32)0x01)<<30))

#define VIDEO_STATUS_FLAGS2_HAS_DEBUG_TIMESTAMPS ((u32)(((u32)0x01)<<8))
#define VIDEO_STATUS_FLAGS2_IS_ON_LOWER_BITRATE ((u32)(((u32)0x01)<<9))
#define VIDEO_STATUS_FLAGS2_IS_NAL_START ((u32)(((u32)0x01)<<10))
#define VIDEO_STATUS_FLAGS2_IS_NAL_END ((u32)(((u32)0x01)<<11))
#define VIDEO_STATUS_FLAGS2_IS_NAL_I ((u32)(((u32)0x01)<<12))
#define VIDEO_STATUS_FLAGS2_IS_NAL_P ((u32)(((u32)0x01)<<13))
#define VIDEO_STATUS_FLAGS2_IS_NAL_OTHER ((u32)(((u32)0x01)<<14))
#define VIDEO_STATUS_FLAGS2_IS_END_OF_FRAME ((u32)(((u32)0x01)<<15))


// Highest bit in video bitrate field tells if vehicle adjusted the videobitrate
#define VIDEO_BITRATE_FLAG_ADJUSTED     ((u32)(((u32)0x01)<<31))
#define VIDEO_BITRATE_FIELD_MASK  0x7FFFFFFF

// Video flags

#define VIDEO_FLAG_ENABLE_FOCUS_MODE_BW      ((u32)0x01)
#define VIDEO_FLAG_ENABLE_LOCAL_HDMI_OUTPUT  ((u32)(((u32)0x01)<<2))
#define VIDEO_FLAG_RETRANSMISSIONS_FAST      ((u32)(((u32)0x01)<<3))
#define VIDEO_FLAG_GENERATE_H265             ((u32)(((u32)0x01)<<4))
#define VIDEO_FLAG_NEW_ADAPTIVE_ALGORITHM    ((u32)(((u32)0x01)<<5))


// Video Important Flags in t_packet_header_video_segment_important
#define VIDEO_IMPORTANT_FLAG_EOF ((u32)0x01)
#define VIDEO_IMPORTANT_FLAG_HAS_DATA_AFTER_EOF ((u32)(((u32)0x01)<<1))

